# ./docker-compose.yml

version: '3.7'

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app
    command:
      - ./wait-for-pg-then-start.sh
    ports:
      - "4000:4000"
  db:
    image: mdillon/postgis:11-alpine
    ports:
      - 15432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
  requestor:
    build:
      context: .
      dockerfile: Dockerfile-curl
    depends_on:
      - app
    volumes:
      - type: bind
        source: .
        target: /app
